# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='CtrlEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aquisicao', models.DateField(auto_now_add=True, verbose_name='Data da aquisição')),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor da compra por unidade')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Fazer reposição',
                'verbose_name_plural': 'Fazer reposições',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.IntegerField(default=0, verbose_name='Desconto')),
                ('data_venda', models.DateField(auto_now_add=True, verbose_name='Data da Venda ')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Cliente')),
            ],
            options={
                'verbose_name': 'Comprar produto',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço do produto')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('desconto', models.IntegerField(default=0, help_text='Aqui você pode colocar um valor padrão de desconto sobre uma peça deste estabelecimento', verbose_name='Porcentagem de desconto')),
                ('onDesconto', models.BooleanField(default=0, help_text='Aqui você tem a opção de ativar ou desativar o desconto', verbose_name='Ativar desconto?')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('preco_servico', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor do serviço')),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo do serviço')),
                ('data_entrega', models.DateField(verbose_name='Data de entrega')),
                ('quantidade', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantidade')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimento.Pedido')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.AddField(
            model_name='ctrlestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimento.Produto', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='addproduto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimento.Pedido'),
        ),
        migrations.AddField(
            model_name='addproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimento.Produto'),
        ),
    ]
